DROP TABLE IF EXISTS public.office_tenants CASCADE;
DROP TABLE IF EXISTS public.tenant CASCADE;

CREATE TABLE public.tenant
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    company_name character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(255) COLLATE pg_catalog."default",
    id_document_number character varying(255) COLLATE pg_catalog."default",
    id_type integer,
    is_private boolean,
    last_name character varying(255) COLLATE pg_catalog."default",
    number_of_employees integer,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(255) COLLATE pg_catalog."default",
    preferred_mean_of_communication integer,
    rejected_reason character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    office_id bigint,
    CONSTRAINT tenant_pkey PRIMARY KEY (id),
    CONSTRAINT uk_1wuu4ilo8ya2tm94iswtp6ev1 UNIQUE (email),
    CONSTRAINT uk_9hhqi4w57c3rldrio34ysagdq UNIQUE (phone_number),
    CONSTRAINT fkisg5lfxogo72qqdehfsxbdshv FOREIGN KEY (office_id)
        REFERENCES public.office (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public.office_tenants
(
    office_id bigint NOT NULL,
    tenants_id bigint NOT NULL,
    CONSTRAINT uk_2rj1e42vyiagec5be997vbvx6 UNIQUE (tenants_id),
    CONSTRAINT fk200dp6uoyxg6m6ap70tiugwk2 FOREIGN KEY (tenants_id)
        REFERENCES public.tenant (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk2pm5xio1tg6ogq0abi94ipovm FOREIGN KEY (office_id)
        REFERENCES public.office (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);