
DROP TABLE IF EXISTS public.office_history CASCADE;
DROP TABLE IF EXISTS public.office CASCADE;

CREATE TABLE public.office
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    city character varying(255) COLLATE pg_catalog."default",
    country character varying(255) COLLATE pg_catalog."default",
    "number" character varying(255) COLLATE pg_catalog."default",
    postal_code character varying(255) COLLATE pg_catalog."default",
    street character varying(255) COLLATE pg_catalog."default",
    area double precision,
    floor integer,
    max_tenants integer,
    room_count integer,
    CONSTRAINT office_pkey PRIMARY KEY (id)
);

CREATE TABLE public.office_history
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    additional_info character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    created_by character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    office_id bigint,
    CONSTRAINT office_history_pkey PRIMARY KEY (id),
    CONSTRAINT office_history_office_id_fkey FOREIGN KEY (office_id)
        REFERENCES public.office (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

