DROP TABLE IF EXISTS public.survey_target CASCADE;
DROP TABLE IF EXISTS public.survey_answer_answers CASCADE;
DROP TABLE IF EXISTS public.survey_answer CASCADE;
DROP TABLE IF EXISTS public.answer CASCADE;
DROP TABLE IF EXISTS public.question CASCADE;
DROP TABLE IF EXISTS public.survey CASCADE;

CREATE TABLE public.survey
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT survey_pkey PRIMARY KEY (id)
);

CREATE TABLE public.question
(
    type character varying(31) COLLATE pg_catalog."default" NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    code character varying(255) COLLATE pg_catalog."default",
    required boolean NOT NULL,
    value character varying(255) COLLATE pg_catalog."default",
    max integer,
    min integer,
    survey_id bigint,
    CONSTRAINT question_pkey PRIMARY KEY (id),
    CONSTRAINT fk65ro96jafjvulbqu8ia0pb254 FOREIGN KEY (survey_id)
        REFERENCES public.survey (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public.answer
(
    answer_type character varying(31) COLLATE pg_catalog."default" NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    boolean_value boolean,
    range_value integer,
    string_value character varying(255) COLLATE pg_catalog."default",
    question_id bigint,
    CONSTRAINT answer_pkey PRIMARY KEY (id),
    CONSTRAINT fk8frr4bcabmmeyyu60qt7iiblo FOREIGN KEY (question_id)
        REFERENCES public.question (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public.survey_answer
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    answered boolean NOT NULL,
    survey_id bigint,
    tenant_id bigint,
    CONSTRAINT survey_answer_pkey PRIMARY KEY (id),
    CONSTRAINT fk2orahwrsoh3de2b3p1a7pv09w FOREIGN KEY (survey_id)
        REFERENCES public.survey (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkkcwy7r9b679nxh7jocyxbjqli FOREIGN KEY (tenant_id)
        REFERENCES public.tenant (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public.survey_answer_answers
(
    survey_answer_id bigint NOT NULL,
    answers_id bigint NOT NULL,
    CONSTRAINT survey_answer_answers_pkey PRIMARY KEY (survey_answer_id, answers_id),
    CONSTRAINT uk_p5rvc8xukas07u0n73vis6kx0 UNIQUE (answers_id),
    CONSTRAINT fk4l3fti85jn9e3v9i9heuuj9xa FOREIGN KEY (survey_answer_id)
        REFERENCES public.survey_answer (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkg9gvulgiln65kxad0jb5o5659 FOREIGN KEY (answers_id)
        REFERENCES public.answer (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public.survey_target
(
    survey_id bigint NOT NULL,
    target_id bigint NOT NULL,
    CONSTRAINT survey_target_pkey PRIMARY KEY (survey_id, target_id),
    CONSTRAINT uk_rs1yb04walyj2s8qnscnxj3fj UNIQUE (target_id),
    CONSTRAINT fk51f4w641kffe1ecaifir5112p FOREIGN KEY (survey_id)
        REFERENCES public.survey (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fka8gwvr0w4xhph6rf6hgue4ral FOREIGN KEY (target_id)
        REFERENCES public.tenant (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);