DROP TABLE IF EXISTS public.landlord;

CREATE TABLE public.landlord
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(255) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT landlord_pkey PRIMARY KEY (id),
    CONSTRAINT uk_5y5jmd99r4204f83jtpacqy6j UNIQUE (email),
    CONSTRAINT uk_ifrjd9smhp9vkke1jj99h9cjj UNIQUE (phone_number)
);